[package]
name = "stylua"
version = "0.1.0-alpha.3"
authors = ["JohnnyMorganz <therobloxbot@gmail.com>"]
description = "A code formatter for Lua"
license = "MPL-2.0"
repository = "https://github.com/johnnymorganz/stylua"
readme = "README.md"
categories = ["command-line-utilities", "development-tools"]
keywords = ["cli", "utility", "lua", "lua51", "formatter"]
edition = "2018"

[lib]
name = "stylua_lib"
path = "src/lib.rs"

[[bin]]
name = "stylua"
path = "src/cli/main.rs"

[features]
default = []
luau = ["full_moon/roblox"]

[dependencies]
anyhow = "1.0.35"
full_moon = { version = "0.9.0" }
glob = "0.3.0"
lazy_static = "1.4.0"
regex = "1.4.2"
serde = "1.0.118"
structopt = "0.3.0"
toml = "0.5.7"